### ISSUE TITLE
singular matrix error

### ISSUE THREAD

**Issue by Showsera** [Choddeok/EmoSphere-TTS#5]
hello, I try `sh preprocessing.sh`, but when initialize training for lda, I receive an error
```
2024-11-22 09:48:47,056 - train_and_align - DEBUG - 	ERROR (est-mllt[5.5]:Invert():matrix/kaldi-matrix.cc:73) Cannot invert: matrix is singular
2024-11-22 09:48:47,056 - train_and_align - DEBUG - 	kaldi::KaldiFatalError
```
If you have encountered similar errors, can you provide some help?
Thank you for your open-source code and reply！

**Comment by Showsera** [comment]
I see your raw_data_dir path is '/workspace/choddeok/hd0/dataset/ESD_mfa_sum', do you have any other preprocessing procedures or just use the raw data directly.
Thank you very much if you can provide some help!

**Comment by Choddeok** [comment]
Thank you for your interest in our paper and code!

Regarding the error message, it would be helpful if you could provide more detailed information so we can offer a more accurate response.

Our preprocessing and code framework follow the same approach as NATSpeech. For more detailed explanations, you may refer to the [NATSpeech repository](https://github.com/NATSpeech/NATSpeech).

Additionally, the raw_data_dir path points to the original dataset directory without any additional preprocessing. The dataset is located at /workspace/choddeok/hd0/dataset/ESD_mfa_sum and is ready for use as is.

We will continue to refine the code and documentation to make it clearer and easier to understand in the future.

Thank you!

**Comment by Showsera** [comment]
Thank you for your reply!
More detailed information is(from train_and_align.log):
```
2024-12-04 16:50:05,226 - train_and_align - DEBUG - There were 1 kaldi processing files that had errors:
2024-12-04 16:50:05,226 - train_and_align - DEBUG - 
2024-12-04 16:50:05,226 - train_and_align - DEBUG - /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/log/transform_means.4.log
2024-12-04 16:50:05,226 - train_and_align - DEBUG - 	/root/Documents/MFA/thirdparty/bin/est-mllt /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/lda_new.mat /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.0.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.1.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.2.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.3.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.4.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.5.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.6.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.7.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.8.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.9.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.10.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.11.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.12.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.13.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.14.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.15.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.16.macc /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.17.macc
2024-12-04 16:50:05,227 - train_and_align - DEBUG - 	ERROR (est-mllt[5.5]:Invert():matrix/kaldi-matrix.cc:73) Cannot invert: matrix is singular
2024-12-04 16:50:05,227 - train_and_align - DEBUG - 	kaldi::KaldiFatalError
2024-12-04 16:50:05,227 - train_and_align - DEBUG - 	/root/Documents/MFA/thirdparty/bin/gmm-transform-means /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/lda_new.mat /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.mdl /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.mdl
2024-12-04 16:50:05,227 - train_and_align - DEBUG - 	LOG (gmm-transform-means[5.5]:main():gmmbin/gmm-transform-means.cc:103) Written model to /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/4.mdl
2024-12-04 16:50:05,227 - train_and_align - DEBUG - 	/root/Documents/MFA/thirdparty/bin/compose-transforms /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/lda_new.mat /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/lda.mat /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/lda/lda_composed.mat
```
and the error happened when training for lda:
```
INFO - Training complete!
INFO - Generating alignments using tri models for the whole corpus...
INFO - Initializing training for lda...
INFO - Initialization complete!

  0%|          | 0/35 [00:00<?, ?it/s]
  6%|▌         | 2/35 [00:05<01:29,  2.70s/it]
  9%|▊         | 3/35 [00:20<04:05,  7.66s/it]
 11%|█▏        | 4/35 [00:25<03:31,  6.84s/it]
 11%|█▏        | 4/35 [00:39<05:06,  9.89s/it]
There was one or more errors when running Kaldi binaries. For more details, please check /mnt/fb/data/emosphere/processed_data/mfa_tmp/mfa_inputs/train_and_align.log
Traceback (most recent call last):
  File "/mnt/fb/EmoSphere-TTS/align_and_binarize.py", line 11, in <module>
    train_mfa_align()
  File "/mnt/fb/EmoSphere-TTS/data_gen/tts/runs/train_mfa_align.py", line 28, in train_mfa_align
    subprocess.check_call(f'{env_str} bash mfa_usr/run_mfa_train_align.sh', shell=True)
  File "/mnt/fb/miniconda3/envs/emosphere/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command 'CORPUS=processed_data NUM_JOB=192 MFA_OUTPUTS=mfa_outputs MFA_INPUTS=mfa_inputs MFA_CMD=train bash mfa_usr/run_mfa_train_align.sh' returned non-zero exit status 1.
```
What's more, I meet the identical error when I try your new code from "EmoSpherepp"

**Comment by Choddeok** [comment]
Thank you for your interest in my paper and code.

The error you mentioned seems to occur during the MFA (Montreal Forced Aligner) extraction process. Based on the information provided, the issue might be caused by:

Directory Path Error:Please ensure that the directory paths specified for the MFA process are correct and match your working environment.
Speaker Count Configuration:Verify that the number of speakers is correctly set in the configuration. An incorrect speaker setup could lead to errors during processing.

For more details on using MFA or understanding its configuration, I recommend referring to the following resources, which the code is based on:
[Montreal Forced Aligner](https://github.com/MontrealCorpusTools/Montreal-Forced-Aligner)
[NATSpeech](https://github.com/NATSpeech/NATSpeech)

I will also review the preprocessing code to address potential issues and provide more detailed explanations, making it easier to use and train.

Apologies for the delayed response, and thank you again for bringing this to my attention. 😊
